Frontdesk/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Frontdesk.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "Frontdesk"
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^$', home,name = 'home'),
    url(r'^all_students/$', Front_all_student,name = 'front_all_student'),
    url(r'^student/(?P<option>[\w-]+)/(?P<sid>[0-9]+)/$', Front_view_edit_student,name = 'front_VED_student'),
    url(r'^student-addmission/(?P<cor>[\w-]+)/(?P<bat>[\w-]+)/(?P<enquiry_id>[\w-]+)/$', Front_add_student,name = 'front_add_student'),
    url(r'^Asign_course/(?P<stu_id>[0-9]+)/(?P<cor>[0-9]+)/(?P<bat>[0-9]+)/$', Front_AsignCourse_ToStudent, name='front_asign_course'),

    ######Enquiry#######
    url(r'^AllEnquiry/$', Front_enquiry, name='front_enquiry'),
    url(r'^Enquiry/(?P<eid>[0-9]+)/(?P<option>[\w-]+)/$', Front_close_or_update_enquiry, name='front_close_or_update'),

    url(r'^enquiry_followup_Reminder/$', Front_enquiry_followup_reminder, name='front_enquiry_followup_reminder'),
    url(r'^enquiry_Previous_followup/$', Front_previous_follow_up, name='front_enquiry_previous_followup'),
    url(r'^import_enquiry/$', Front_Import_Enquiry, name='front_import_enquiry'),

######### Fee Pay ############
    url(r'^student_Fee_details/(?P<cor>[\w-]+)/(?P<bat>[\w-]+)/$', Front_student_collect_fee, name='front_fee_details'),
    url(r'^Fee_collection_reminder/$', Front_fee_collection_reminder, name='front_fee_collection_reminder'),
    url(r'^Copmplete_Fee_paid_list/$', Front_Complete_FeePaidList, name='front_complete_fee_paid'),

########## All Courses and THeir Details ###########
    url(r'^AllCourse/$', Front_Total_Courses, name='front_total_course'),
    url(r'^Course_Details/(?P<course_id>[0-9]+)$', Front_Course_Details, name='front_details_course'),


########### Cancal Addmission ################</a>
    url(r'^student_cancal_addmission/$', Front_CancalAddmission, name='front_cancal_addmission'),

    url(r'^student_cancal_addmission_List/(?P<cor>[\w-]+)/$', Front_Cancal_AddmissionList, name='front_cancal_addmission_list'),

########## Filter Students ############
    url(r'^filter_students/(?P<cor>[\w-]+)/(?P<bat>[\w-]+)/$', Front_filter_students, name='front_filter_student'),

########### Generate Invoice ###########
    url(r'^student_invoice/(?P<pid>[0-9]+)/$', Front_generate_invoice, name='front_student_invoice'),
################## Upload Document#########

    url(r'^Document/(?P<cor>[0-9]+)/(?P<opt>[\w-]+)/$', Front_UploadDoc_or_GenerateIdCard, name='front_upload_doc_or_idcard'),
    url(r'^student/(?P<sid>[0-9]+)/(?P<op>[\w-]+)/$', Front_single_student_doc_idcard, name='front_single_s_doc_id'),
    url(r'^All_uploaded_Documents/$', All_Batch_uploaded_documents, name='front_all_uploded'),
    url(r'^All_Receipts/$', Front_all_receipts, name='front_all_receipts'),
    url(r'^Staff_id_cards/$', Front_staff_id_card, name='front_staff_idcard'),
   #################### Notification #################
   url(r'^notification_batch/(?P<cour>[\w-]+)/(?P<batch>[\w-]+)/$', Notification_for_Batch, name='notification_batch'),
   url(r'^notification_for_all_students/(?P<option>[\w-]+)/$', Notification_for_allstudents_or_staff, name='notification_all_stu_or_staff'),
   url(r'^select_student/(?P<cour>[\w-]+)/(?P<batch>[\w-]+)/$',
        Select_student_for_notifi, name='select_student'),
   url(r'^Select_Enquiry_student/(?P<cor>[\w-]+)/$', Select_enquiry_students, name='select_enq_students'),
   url(r'^Notification_for_Enquiry_student/(?P<enq_data>[\w-]+)/$', Notification_Enquiry_students, name='notification_enquiry_student'),



   url(r'^notification_for_single_student/(?P<ndata>[\w-]+)/$', Notification_for_single_student, name='notification_for_single'),
   url(r'^notification_for_single_staff/$', Notification_for_single_staff, name='notification_for_single_staff'),
   #############Call Logs #################
   url(r'^all_call_logs/$', Front_student_call_logs, name='call_logs'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "StudentPanel"
urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^$', Dashboard, name = 'home'),
url(r'^Add_link/(?P<option>[\w-]+)/$', Students_Link_add, name = 'students_links'),
url(r'^profile/$', Student_profile, name = 'profile'),
url(r'^Change_password/$', Chenge_password, name = 'change_password'),
url(r'^Edit_profile/$', Student_edit_profile, name = 'edit_profile'),
url(r'^test_list/$', AllTests, name = 'tests'),
url(r'^exams_list/(?P<pid>[\w-]+)/$', All_Exams, name = 'exams'),
url(r'^Generate_invoice/(?P<pid>[0-9]+)/$', Student_generate_invoice, name = 'invoice'),




url(r'^test_instruction/(?P<eid>[\w-]+)/$', TestInstruction, name = 'instruction'),
url(r'^test_live/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', LiveTest, name = 'live'),
url(r'^analysis/(?P<eid>[\w-]+)/$', TestAnalysis, name = 'analysis'),
url(r'^Exam_Solution/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', ExamSolution, name = 'solution'),



url(r'^practice/$', Practice, name = 'practice'),
url(r'^practice_questions/$', PracticeQuestion, name = 'practice_questions'),
url(r'^single_question/$', StartPractice, name = 'single_question'),

url(r'^quiz/$', AllQuiz, name = 'quiz'),
url(r'^start_quiz/(?P<qid>[\w-]+)/(?P<q_id>[\w-]+)/(?P<time>[\w-]+)/$', StartQuiz, name = 'start_quiz'),
url(r'^quiz_summery/(?P<qid>[\w-]+)/analysis_Answers/$', QuizSummery, name = 'quiz_summery'),
url(r'^quiz_solution/(?P<qid>[\w-]+)/Answers/(?P<q_id>[\w-]+)/$', QuizSolution, name = 'quiz_solution'),



url(r'^study_material/$', Study_Material, name = 'study_material'),
url(r'^courses/$', Courses, name = 'courses'),
url(r'^fee/$', FeeDetails, name = 'FeeDetails'),
url(r'^invoice/$', Invoice, name = 'invoice'),

url(r'^Installment_details/(?P<cid>[0-9]+)/$', FeeInstallmentDetails, name = 'installment_details'),
url(r'^Notifications/$', Student_Notifications, name = 'student_notification'),
url(r'^Uploaded_Document/$', Student_Upload_Documents, name = 'student_upload_document'),
url(r'^E_corner/$', Student_Ecorner, name = 'student_ecorner'),
url(r'^Issued_Returned_Book/$', Student_issued_returned_book, name = 'issue_return_book'),


]

django_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Institute.views import *
from django.conf import settings
from django.conf.urls.static import static
from WebSite.views import *


urlpatterns = [
    url(r'^register/$', Register, name = "register"),
    url(r'^forgot_password/$', ForgotPass, name = "Forgot"),
    url(r'^login/$', Login, name = "login"),
    url(r'^$', Website_home, name = "website_home"),
    url(r'^SkyLark/$', Start, name = "demo"),
    url(r'^logout$', Logout, name = "logout"),
    url(r'^frontdesk/', include('Frontdesk.urls', namespace='Frontdesk')),
    url(r'^Student_panel/', include('Student.urls', namespace='StudentPanel')),
    url(r'^website/', include('WebSite.urls', namespace='Website')),

    url(r'^exam_controller/', include('ExamPanel.urls', namespace='ExamPanel')),
    url(r'^library_panel/', include('LibraryPanel.urls', namespace='LibraryPanel')),
    url(r'^master_panel/', include('Institute.urls', namespace='Master')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Frontdesk/models.py
from django.db import models
from Institute.models import *
from django.forms import ModelForm

COLOR_CHOICES = (
    ('','Gender'),
    ('male','Male'),
    ('female', 'Female'),

)



class Front_student_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    usr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    ##### Basic Details #######
    roll_number = models.CharField(max_length=100,null=True,blank=True)
    image = models.FileField(null=True, blank=True)
    name = models.CharField(max_length=100,null=True,blank=True)
    dob = models.CharField(max_length=10, null=True,blank=True)
    address = models.TextField(max_length=500, null=True,blank=True)
    mobile = models.CharField(max_length=13, null=True,blank=True)
    email = models.CharField(max_length=100, null=True,blank=True)
    college = models.CharField(max_length=100, null=True,blank=True)
    graduation = models.CharField(max_length=100, null=True,blank=True)
    stream = models.CharField(max_length=100, null=True,blank=True)
    gender = models.CharField(max_length=10,choices=COLOR_CHOICES,default='Gender')
    #### Parents Details #########
    Father_name = models.CharField(max_length=100, null=True,blank=True)
    father_mob = models.CharField(max_length=13, null=True,blank=True)
    Occupation = models.CharField(max_length=100, null=True,blank=True)
    father_add = models.CharField(max_length=200, null=True,blank=True)
    status = models.CharField(max_length=20,null=True,blank=True)
    id_card_validity = models.CharField(max_length=10,null=True,blank=True)



    def __str__(self):
        return self.name

class Front_cancal_addmission_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Front_student_data,models.CASCADE,null=True)
    course = models.ForeignKey(Master_course_data,models.CASCADE,null=True)
    batch = models.ForeignKey(Master_batch_data,models.CASCADE,null=True)
    refund_money = models.CharField(max_length=100,null=True,blank=True)
    cancal_date = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.student.name + ' course ' + self.course.name

class Front_student_course_batch_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    ##### Course Details ########
    student = models.ForeignKey(Front_student_data,models.CASCADE,null=True,blank=True)
    course = models.ForeignKey(Master_course_data, models.CASCADE, null=True,
                               default='', blank=True)
    Batch = models.ForeignKey(Master_batch_data, models.CASCADE, null=True, default='', blank=True)
    addmission_date = models.CharField(max_length=100, null=True, blank=True)
    total_fee_pay = models.CharField(max_length=100, null=True, blank=True)
    fee_after_pay = models.CharField(max_length=100, null=True, blank=True)
    ##### Fee Details #######
    discount = models.CharField(max_length=100, null=True, blank=True)
    total_fee = models.CharField(max_length=100, null=True, blank=True)
    course_cancel_date = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.student.name + ' -course-- ' + self.course.name + '- batch-- ' + self.Batch.name


class Front_student_fee_type_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student_course = models.ForeignKey(Front_student_course_batch_data,models.CASCADE,null=True)
    name =  models.CharField(max_length=100,null=True)
    fee =  models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.student_course.student.name + '--' + self.name + '--' + self.fee

class Front_student_fee_installment_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student_course = models.ForeignKey(Front_student_course_batch_data,models.CASCADE,null=True)
    installment = models.CharField(max_length=100,null=True)
    amount = models.CharField(max_length=100,null=True)
    pay_fee = models.CharField(max_length=100,null=True)
    remaining_fee = models.CharField(max_length=100,null=True)
    installment_last_date = models.CharField(max_length=100,null=True)


    def __str__(self):
        return self.student_course.student.name + ' ' + self.installment + ' amount ' + self.amount

class Front_student_pay_fee(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student_course = models.ForeignKey(Front_student_course_batch_data, models.CASCADE, null=True)
    payment_mode_cash = models.CharField(max_length=100,null=True,blank=True)
    amount = models.CharField(max_length=100,null=True,blank=True)
    payment_mode_cheque = models.CharField(max_length=100,null=True,blank=True)
    cheque_number =  models.CharField(max_length=100,null=True,blank=True)
    Bank_name = models.CharField(max_length=100, null=True,blank=True)
    cheque_date = models.CharField(max_length=100, null=True,blank=True)
    payment_date = models.CharField(max_length=100,null=True,blank=True)
    remain_ammount = models.CharField(max_length=100,null=True,blank=True)
    total_amount = models.CharField(max_length=100,null=True,blank=True)
    invoice_number = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.student_course.student.name + ' payment_date ' + self.payment_date



class Front_enquiry_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Master_course_data,models.CASCADE,null=True ,default='')
    student_name = models.CharField(max_length=100,null=True)
    father_name = models.CharField(max_length=100,null=True,blank=True)
    college = models.CharField(max_length=100,null=True,blank=True)
    graduation = models.CharField(max_length=100,null=True,blank=True)
    mobile = models.CharField(max_length=13,null=True)
    email = models.CharField(max_length=100,null=True)
    address = models.CharField(max_length=100,null=True)
    follow_up_date = models.CharField(max_length=10,null=True)
    follow_up_time = models.CharField(max_length=100, null=True)
    remark = models.CharField(max_length=500,null=True)
    visited_date = models.CharField(max_length=100,null=True,blank=True)
    todays_follow_up_date = models.CharField(max_length=100, null=True,blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)
    course_name = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.student_name

##########Invoice Number #############

class Invoice_number_generate(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    start_char = models.CharField(max_length=100,null=True,blank=True)
    number = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return 'number ' + str(self.number)


class Institute_number(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    ins_short_name = models.CharField(max_length=100,null=True,blank=True)
    number = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.ins_short_name + ' number ' + str(self.number)


class Front_document_files(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Front_student_data,models.CASCADE,null=True)
    doc_name = models.CharField(max_length=100,null=True)
    document_file = models.FileField(null=True)
    doc_file_name = models.CharField(max_length=100,null=True)
    upload_date = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.student.name

class Front_All_Uploaded_document(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    batch = models.ForeignKey(Master_batch_data,models.CASCADE,null=True)
    doc_name = models.CharField(max_length=100,null=True)
    doc_file = models.FileField(null=True)
    upload_date = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.batch.name


class Todays_follow_up_date(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    fdate = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.fdate


##################### NOTIFICATION ##########

class Notification_on_panel(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Front_student_data, on_delete=models.CASCADE)
    info = models.CharField(max_length=2000, null=True, blank=True)
    noti_date =models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.student.name


################# Call Logs ###############

class Front_call_logs(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Master_course_data,null=True, on_delete=models.CASCADE,default='')
    student_name = models.CharField(max_length=100,null=True,blank=True)
    mobile = models.CharField(max_length=100,null=True,blank=True)
    call_date = models.CharField(max_length=100,null=True,blank=True)
    next_follow_up_date = models.CharField(max_length=10,null=True,blank=True)
    remark = models.CharField(max_length=100,null=True,blank=True)
    follow_up_time = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.course.name + ' - ' + self.student_name

Frontdesk/templates/front/front_base.html
{% block up %}
{% endblock %}

{% load static %}
<link rel="icon" href="{{ ins_data.institute_logo.url }}" type="image/x-icon"> <!-- Favicon-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<body class="theme-cyan menu_dark">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30"><img class="zmdi-hc-spin" src="{{ ins_data.institute_logo.url }}" style="border-radius: 50%;" width="48" height="48" alt="{{ ins_data.name }}"></div>
        <p>Please wait...</p>
    </div>
</div>
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- Top Bar -->
<nav class="navbar p-l-5 p-r-5">
    <ul class="nav navbar-nav navbar-left">
        <li>
            <div class="navbar-header">
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href=""><img src="{{ ins_data.institute_logo.url }}" width="30" style="border-radius: 50%;" alt="Logo">

                         {% if request.user.last_name == "Admin" %}
                            {% if not request.user.is_staff %}
                                <span class="m-l-10">{{ request.user.visiteduser_set.first.institute }}</span></a>
                            {% else %}
                                <span class="m-l-10">{{ ins_data.name }}</span></a>
                            {% endif %}
                        {% else %}
                                <span class="m-l-10">{{ ins_data.name }}</span></a>
                        {% endif %}

            </div>
        </li>
        <li><a href="javascript:void(0);" class="ls-toggle-btn" data-close="true"><i class="zmdi zmdi-swap"></i></a></li>

        <li class="float-right">

            <a href="{% url 'logout' %}" class="mega-menu" data-close="true"><i class="zmdi zmdi-power"></i></a>

        </li>
    </ul>
</nav>
<!-- Left Sidebar-->
<aside id="leftsidebar" class="sidebar">
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link " data-toggle="tab" href="#dashboard"></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane stretchRight active" id="dashboard">
            <div class="menu">
                <ul class="list">
                    <li>
                        {% if request.user.last_name == "Admin" %}
                        <div class="user-info">
                            <div class="image"><a href=""><img src="{{ adminprofile.image.url }}" alt="{{ adminprofile.name }}"></a></div>
                            <div class="detail">
                                <h4>{{ adminprofile.name }}</h4>
                                <small>Admin</small>
                            </div>
                        </div>
                        {% else %}
                        <div class="user-info">
                            <div class="image"><a href=""><img src="{{ request.user.user_management_set.first.emp.image.url }}" alt="{{ request.user.admin_profile_set.first.name }}"></a></div>
                            <div class="detail">
                                <h4>{{ request.user.user_management_set.first.emp.name }}</h4>
                                <small>{{ request.user.user_management_set.first.emp.designation }}</small>
                            </div>
                        </div>
                        {% endif %}
                    </li>

                    <li><a href="{% url 'Frontdesk:home' %}"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a></li>

                    <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-library"></i><span>Enquiry</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_enquiry' %}">All Enquiry</a></li>

                        </ul>
                    </li>
                    <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-phone"></i><span>Call Logs</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:call_logs' %}">All call logs</a></li>

                        </ul>
                    </li>

					 <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-pin-account"></i><span>Admission</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_add_student' '0' '0' '0' %}">Admission</a></li>
                        </ul>
                    </li>
                     <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-account-circle"></i><span>Students</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_all_student' %}">All Students</a></li>
                            <li><a href="{% url 'Frontdesk:front_filter_student'  '0' '0' %}">Filter Students</a></li>
                            <li><a href="{% url 'Frontdesk:front_cancal_addmission_list' '0' %}">Admission Cancal List</a></li>


                        </ul>
                    </li>

					<li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-balance"></i><span>Accounting</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_fee_details' '0' '0' %}">Collect Fee</a></li>
                            <li><a href="{% url 'Frontdesk:front_complete_fee_paid' %}">Complete Fee Paid List</a></li>

                        </ul>
                    </li>

					<li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-card"></i><span>Generate Id Card</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_upload_doc_or_idcard' '0' 'Idcard' %}">Student Id Card</a></li>
                            <li><a href="{% url 'Frontdesk:front_staff_idcard' %}">Staff Id Card</a></li>


                        </ul>
                    </li>

					 <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-alarm"></i><span>Reminders</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_enquiry_previous_followup' %}">Previous Follow Up's</a></li>

                            <li><a href="{% url 'Frontdesk:front_enquiry_followup_reminder' %}">Upcoming Follow Up's</a></li>
                            <li><a href="{% url 'Frontdesk:front_fee_collection_reminder' %}">Fee Collection Reminder</a></li>

                        </ul>
                    </li>
                    <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-upload"></i><span>Upload Document</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_upload_doc_or_idcard' '0' 'UploadDoc' %}">Upload Document</a></li>
                            <li><a href="{% url 'Frontdesk:front_all_uploded' %}">Uploaded Document List</a></li>

                        </ul>
                    </li>
                    <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-notifications-active"></i><span>Notifications</span> </a>
                        <ul class="ml-menu">
                           <li><a href="{% url 'Frontdesk:notification_batch' '0' '0' %}">Batch Students</a></li>
                            <li><a href="{% url 'Frontdesk:select_student' '0' '0' %}">Individual Student</a></li>
                            <li><a href="{% url 'Frontdesk:select_enq_students' '0' %}">For Enquiry Students</a></li>

                            <li><a href="{% url 'Frontdesk:notification_all_stu_or_staff' 'AllStaff' %}">For All Staff</a></li>
                            <li><a href="{% url 'Frontdesk:notification_for_single_staff' %}">Individual Staff Member</a></li>

                        </ul>
                    </li>
                    <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-copy"></i><span>Receipts</span> </a>
                        <ul class="ml-menu">
                            <li><a href="{% url 'Frontdesk:front_all_receipts' %}">All Receipts</a></li>

                        </ul>
                    </li>
                    <li>
                        <ul class="ml-menu">
                            <li></li>
                        </ul>
                    </li>
                    <li>
                        <ul class="ml-menu">
                            <li></li>
                        </ul>
                    </li>



                </ul>
            </div>
        </div>
    </div>
</aside>



{% block down %}
{% endblock %}