Student/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "StudentPanel"
urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^$', Dashboard, name = 'home'),
url(r'^Add_link/(?P<option>[\w-]+)/$', Students_Link_add, name = 'students_links'),
url(r'^profile/$', Student_profile, name = 'profile'),
url(r'^Change_password/$', Chenge_password, name = 'change_password'),
url(r'^Edit_profile/$', Student_edit_profile, name = 'edit_profile'),
url(r'^test_list/$', AllTests, name = 'tests'),
url(r'^exams_list/(?P<pid>[\w-]+)/$', All_Exams, name = 'exams'),
url(r'^Generate_invoice/(?P<pid>[0-9]+)/$', Student_generate_invoice, name = 'invoice'),




url(r'^test_instruction/(?P<eid>[\w-]+)/$', TestInstruction, name = 'instruction'),
url(r'^test_live/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', LiveTest, name = 'live'),
url(r'^analysis/(?P<eid>[\w-]+)/$', TestAnalysis, name = 'analysis'),
url(r'^Exam_Solution/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', ExamSolution, name = 'solution'),



url(r'^practice/$', Practice, name = 'practice'),
url(r'^practice_questions/$', PracticeQuestion, name = 'practice_questions'),
url(r'^single_question/$', StartPractice, name = 'single_question'),

url(r'^quiz/$', AllQuiz, name = 'quiz'),
url(r'^start_quiz/(?P<qid>[\w-]+)/(?P<q_id>[\w-]+)/(?P<time>[\w-]+)/$', StartQuiz, name = 'start_quiz'),
url(r'^quiz_summery/(?P<qid>[\w-]+)/analysis_Answers/$', QuizSummery, name = 'quiz_summery'),
url(r'^quiz_solution/(?P<qid>[\w-]+)/Answers/(?P<q_id>[\w-]+)/$', QuizSolution, name = 'quiz_solution'),



url(r'^study_material/$', Study_Material, name = 'study_material'),
url(r'^courses/$', Courses, name = 'courses'),
url(r'^fee/$', FeeDetails, name = 'FeeDetails'),
url(r'^invoice/$', Invoice, name = 'invoice'),

url(r'^Installment_details/(?P<cid>[0-9]+)/$', FeeInstallmentDetails, name = 'installment_details'),
url(r'^Notifications/$', Student_Notifications, name = 'student_notification'),
url(r'^Uploaded_Document/$', Student_Upload_Documents, name = 'student_upload_document'),
url(r'^E_corner/$', Student_Ecorner, name = 'student_ecorner'),
url(r'^Issued_Returned_Book/$', Student_issued_returned_book, name = 'issue_return_book'),


]

django_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Institute.views import *
from django.conf import settings
from django.conf.urls.static import static
from WebSite.views import *


urlpatterns = [
    url(r'^register/$', Register, name = "register"),
    url(r'^forgot_password/$', ForgotPass, name = "Forgot"),
    url(r'^login/$', Login, name = "login"),
    url(r'^$', Website_home, name = "website_home"),
    url(r'^SkyLark/$', Start, name = "demo"),
    url(r'^logout$', Logout, name = "logout"),
    url(r'^frontdesk/', include('Frontdesk.urls', namespace='Frontdesk')),
    url(r'^Student_panel/', include('Student.urls', namespace='StudentPanel')),
    url(r'^website/', include('WebSite.urls', namespace='Website')),

    url(r'^exam_controller/', include('ExamPanel.urls', namespace='ExamPanel')),
    url(r'^library_panel/', include('LibraryPanel.urls', namespace='LibraryPanel')),
    url(r'^master_panel/', include('Institute.urls', namespace='Master')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ExamPanel/models.py
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from Institute.models import *
from Frontdesk.models import *
from WebSite.models import *
class ExamPackage(models.Model):
    course = models.ForeignKey(Sub_course, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    fee = models.CharField(max_length=10, null=True, blank=True)
    o_fee = models.CharField(max_length=10, null=True, blank=True)
    logo = models.FileField(null=True, blank=True)
    syllabus = models.FileField(null=True, blank=True)
    status = models.CharField(max_length=150, default="UnPublish")

    def __str__(self):
        return self.name + "------" + self.course.name



class ExamSubPackage(models.Model):
    course = models.ForeignKey(Sub_course, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class Package_Subpackage(models.Model):
    package = models.ForeignKey(ExamPackage, on_delete=models.CASCADE, null=True)
    sub = models.ForeignKey(ExamSubPackage, on_delete=models.CASCADE, null=True)



class MainExam(models.Model):
    course = models.ForeignKey(Sub_course, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    start_date = models.CharField(max_length=100, null=True, blank=True)
    end_date = models.CharField(max_length=100, null=True, blank=True)
    duration = models.CharField(max_length=10, null=True, blank=True)
    instruction = RichTextUploadingField(blank=True, null=True)
    syllabus = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name


class SubPackage_MainExam(models.Model):
    sub = models.ForeignKey(ExamSubPackage, on_delete=models.CASCADE, null=True)
    main = models.ForeignKey(MainExam, on_delete=models.CASCADE, null=True)



class MainExamSection(models.Model):
    exam = models.ForeignKey(MainExam, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


Ans = [
    ['1', '1'],
    ['2', '2'],
    ['3', '3'],
    ['4', '4'],
]


Ans1 = [
    ['0', 'Select'],
    ['1', 'True'],
    ['2', 'False']
]

class Question_Section(models.Model):
    course = models.ForeignKey(Sub_course, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)


class MultipleChoiceQuestions(models.Model):
    section = models.ForeignKey(Question_Section, on_delete=models.SET_NULL, null=True)
    Type1 = models.BooleanField(default=False)
    Questions = RichTextUploadingField(blank=True, null=True)
    Option_1 = RichTextUploadingField(blank=True, null=True)
    Option_2 = RichTextUploadingField(blank=True, null=True)
    Option_3 = RichTextUploadingField(blank=True, null=True)
    Option_4 = RichTextUploadingField(blank=True, null=True)
    TrueAns = models.CharField(max_length=5, choices=Ans, default='1', null=True)
    marks1 = models.CharField(max_length=5, null=True, blank=True)
    minus1 = models.CharField(max_length=20, null=True)
    explain1 = RichTextUploadingField(blank=True, null=True)

    Type2 = models.BooleanField(default=False)
    Question = RichTextUploadingField(blank=True, null=True)
    Option1 = RichTextUploadingField(blank=True, null=True)
    Option2 = RichTextUploadingField(blank=True, null=True)
    Option3 = RichTextUploadingField(blank=True, null=True)
    Option4 = RichTextUploadingField(blank=True, null=True)
    Answer1 = models.BooleanField(default=False)
    Answer2 = models.BooleanField(default=False)
    Answer3 = models.BooleanField(default=False)
    Answer4 = models.BooleanField(default=False)
    marks2 = models.CharField(max_length=5, null=True, blank=True)
    minus2 = models.CharField(max_length=20, null=True)
    explain2 = RichTextUploadingField(blank=True, null=True)

    Type3 = models.BooleanField(default=False)
    Que = RichTextUploadingField(blank=True, null=True)
    Answer31 = models.CharField(max_length=250, null=True, blank=True)
    Answer32 = models.CharField(max_length=250, null=True, blank=True)
    marks3 = models.CharField(max_length=5, null=True, blank=True)
    minus3 = models.CharField(max_length=20, null=True)
    explain3 = RichTextUploadingField(blank=True, null=True)

    Type4 = models.BooleanField(default=False)
    Ques_tion = RichTextUploadingField(blank=True, null=True)
    TrueAns1 = models.CharField(max_length=5, choices=Ans1, default='0')
    marks4 = models.CharField(max_length=5, null=True, blank=True)
    minus4 = models.CharField(max_length=20, null=True)
    explain4 = RichTextUploadingField(blank=True, null=True)



class ExamQuestion(models.Model):
    MainSection = models.ForeignKey(MainExamSection, on_delete=models.CASCADE)
    Question = models.ForeignKey(MultipleChoiceQuestions, on_delete=models.CASCADE)

    def __str__(self):
        return self.Question.Questions



class QuizPackage(models.Model):
    course = models.ForeignKey(Sub_course, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    logo = models.FileField(null=True, blank=True)
    fee = models.CharField(max_length=10, null=True, blank=True, default=0)
    o_fee = models.CharField(max_length=10, null=True, blank=True, default=0)
    syllabus = models.FileField(null=True, blank=True)
    status = models.CharField(max_length=150, default="UnPublish")


class Quiz(models.Model):
    course = models.ForeignKey(Sub_course, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    duration = models.CharField(max_length=10, null=True, blank=True)
    start_date = models.CharField(max_length=100, null=True, blank=True)
    end_date = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.name


class Quiz_QuizPackage(models.Model):
    package = models.ForeignKey(QuizPackage, on_delete=models.CASCADE, null=True)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)


class Quiz_Questions(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    Question = models.ForeignKey(MultipleChoiceQuestions, on_delete=models.CASCADE)



class DailyPracticeSubject(models.Model):
    course = models.ForeignKey(Sub_course, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    logo = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.name + " / Course:" + self.course.name


class Topic(models.Model):
    package = models.ForeignKey(DailyPracticeSubject, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)



class Topic_Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    Question = models.ForeignKey(MultipleChoiceQuestions, on_delete=models.CASCADE, null=True)



class StudyMaterial(models.Model):
    course = models.ForeignKey(Master_course_data, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=250, null=True, blank=True)
    date = models.CharField(max_length=250, null=True, blank=True)
    file = models.FileField(null=True, blank=True)


class Material_Batch(models.Model):
    batch = models.ForeignKey(Master_batch_data, on_delete=models.CASCADE, null=True)
    material = models.ForeignKey(StudyMaterial, on_delete=models.CASCADE, null=True)

Gender = [
    ['Male', 'Male'],
    ['Female', 'Female']
]


class StudentQuestions(models.Model):
    section = models.ForeignKey(Question_Section, on_delete=models.SET_NULL, null=True)
    Type1 = models.BooleanField(default=False)
    Questions = RichTextUploadingField(blank=True, null=True)
    Option_1 = RichTextUploadingField(blank=True, null=True)
    Option_2 = RichTextUploadingField(blank=True, null=True)
    Option_3 = RichTextUploadingField(blank=True, null=True)
    Option_4 = RichTextUploadingField(blank=True, null=True)
    TrueAns = models.CharField(max_length=5, choices=Ans, default='1', null=True, blank=True)
    marks1 = models.CharField(max_length=5, null=True, blank=True)
    minus1 = models.CharField(max_length=20, null=True)
    explain1 = RichTextUploadingField(blank=True, null=True)

    Type2 = models.BooleanField(default=False)
    Question = RichTextUploadingField(blank=True, null=True)
    Option1 = RichTextUploadingField(blank=True, null=True)
    Option2 = RichTextUploadingField(blank=True, null=True)
    Option3 = RichTextUploadingField(blank=True, null=True)
    Option4 = RichTextUploadingField(blank=True, null=True)
    Answer1 = models.BooleanField(default=False)
    Answer2 = models.BooleanField(default=False)
    Answer3 = models.BooleanField(default=False)
    Answer4 = models.BooleanField(default=False)
    marks2 = models.CharField(max_length=5, null=True, blank=True)
    minus2 = models.CharField(max_length=20, null=True, blank=True)
    explain2 = RichTextUploadingField(blank=True, null=True)

    Type3 = models.BooleanField(default=False)
    Que = RichTextUploadingField(blank=True, null=True)
    Answer31 = models.CharField(max_length=250, null=True, blank=True)
    Answer32 = models.CharField(max_length=250, null=True, blank=True)
    marks3 = models.CharField(max_length=5, null=True, blank=True)
    minus3 = models.CharField(max_length=20, null=True)
    explain3 = RichTextUploadingField(blank=True, null=True)

    Type4 = models.BooleanField(default=False)
    Ques_tion = RichTextUploadingField(blank=True, null=True)
    TrueAns1 = models.CharField(max_length=5, choices=Ans1, default='0')
    marks4 = models.CharField(max_length=5, null=True, blank=True)
    minus4 = models.CharField(max_length=20, null=True)
    explain4 = RichTextUploadingField(blank=True, null=True)

class Add_New_Student(models.Model):

Student/models.py
from django.db import models
from Frontdesk.models import *



class Student_add_link(models.Model):
    student = models.ForeignKey(Front_student_data,on_delete=models.CASCADE,null=True)
    facebook_link = models.CharField(max_length=500,null=True,blank=True)
    twitter_link = models.CharField(max_length=500, null=True, blank=True)
    instagram_link = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.student.name

Student/templates/StudentHome/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
<title>:: {{ student.name }} :: Student Panel</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="Mplify Bootstrap 4.1.1 Admin Template">
<meta name="author" content="ThemeMakker, design by: ThemeMakker.com">

<link rel="icon" href="{{ ins_data.ins.institute_logo.url }}">
<!-- VENDOR CSS -->
<link rel="stylesheet" href="{% static 'student/assets1/vendor/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'student/assets1/vendor/animate-css/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'student/assets1/vendor/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'student/assets1/vendor/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}">
<link rel="stylesheet" href="{% static 'student/assets1/vendor/chartist/css/chartist.min.css' %}">
<link rel="stylesheet" href="{% static 'student/assets1/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css' %}">

<!-- MAIN CSS -->
<link rel="stylesheet" href="{% static 'student/assets/css/main.css' %}">
<link rel="stylesheet" href="{% static 'student/assets/css/color_skins.css' %}">
    <script src="{% static 'aes.js' %}"></script>

<style>
.dot {
    height: 40px;
    width: 40px;
    background-color: #092C35;
    border-radius: 50%;
    display: inline-block;
        border-width: 5px;
        color: white;
    border: 1px solid #51647a;

}

.cdot {
    height: 35px;
    width: 35px;
    background-color: #AAB7B8;
    border-radius: 50%;
    display: inline-block;
        border-width: 5px;
        color: white;
    border: 1px solid #AAB7B8;
    padding-bottom: 30px;

}

</style>


<script>
function Uncheck() {
    var ele = document.getElementsByName("ans");
    for(var i=0;i<ele.length;i++)
      ele[i].checked = false;
}
</script>


</head>
<body class="theme-cyan">

<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30"><img class="zmdi-hc-spin" src="{{ ins_data.ins.institute_logo.url }}" style="border-radius:50%;" width="48" height="48" alt="{{ ins_data.ins.name }}"></div>
        <p>Please wait...</p>
    </div>
</div>
<!-- Overlay For Sidebars -->
<div class="overlay" style="display: none;"></div>

<div id="wrapper">

    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-brand">
                <a href="">

                    <img src="{{ ins_data.ins.institute_logo.url }}" alt="{{ ins_data.ins.name }}" style="border-radius:50%;" class="img-responsive logo">
                    <span class="name" style="font-size:15px;">{{ ins_data.ins.name }}</span>
                </a>
            </div>

            <div class="navbar-right">
                <ul class="list-unstyled clearfix mb-0">
                    <li>
                        <div class="navbar-btn btn-toggle-show">
                            <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                        </div>
                        <a href="javascript:void(0);" class="btn-toggle-fullwidth btn-toggle-hide"><i class="fa fa-bars"></i></a>
                    </li>

                    <li>
                        <div id="navbar-menu">
                            <ul class="nav navbar-nav">
                                {% if request.user.last_name == "I_Student" %}
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                    {% if request.user.front_student_data_set.first.image %}
                                        <img class="rounded-circle" src="{{ request.user.front_student_data_set.first.image.url }}" width="30" height="30" alt="">{% endif %}
                                    </a>
                                    <div class="dropdown-menu animated flipInY user-profile">
                                        <div class="d-flex p-3 align-items-center">
                                            <div class="drop-left m-r-10">
                                                {% if request.user.front_student_data_set.first.image %}
                                                <img src="{{ request.user.front_student_data_set.first.image.url }}" class="rounded" width="50" alt="">{% endif %}
                                            </div>
                                            <div class="drop-right">
                                                <h4>{{ request.user.front_student_data_set.first.name }}</h4>
                                                <p class="user-name">{{ request.user.front_student_data_set.first.email }}</p>
                                            </div>
                                        </div>
                                        <div class="m-t-10 p-3 drop-list">
                                            <ul class="list-unstyled">
                                                <li><a href="{% url 'StudentPanel:profile' %}"><i class="icon-user"></i>My Profile</a></li>

                                                <li><a href="{% url 'StudentPanel:edit_profile' %}"><i class="icon-pencil"></i>Edit Profile</a></li>
                                                <li><a href="{% url 'StudentPanel:change_password' %}"><i class="fa fa-eraser"></i>Change Password</a></li>

                                                <li class="divider"></li>
                                                <li><a href="{% url 'logout' %}"><i class="icon-power"></i>Logout</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                {% endif %}
                                {% if request.user.last_name == "E_Student" %}
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                        <img class="rounded-circle" src="{{ request.user.add_new_student_set.first.photo.url }}" width="30" height="30" alt="">
                                    </a>
                                    <div class="dropdown-menu animated flipInY user-profile">
                                        <div class="d-flex p-3 align-items-center">
                                            <div class="drop-left m-r-10">
                                                <img src="{{ request.user.add_new_student_set.first.photo.url }}" class="rounded-circle" width="50" alt="">
                                            </div>
                                            <div class="drop-right">
                                                <h4>{{ request.user.add_new_student_set.first.name }}</h4>
                                                <p class="user-name">{{ request.user.add_new_student_set.first.email }}</p>
                                            </div>
                                        </div>
                                        <div class="m-t-10 p-3 drop-list">
                                            <ul class="list-unstyled">
                                                <li class="divider"></li>
                                                <li><a href="{% url 'logout' %}"><i class="icon-power"></i>Logout</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                {% endif %}
                            
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="leftsidebar" class="sidebar">
        <div class="sidebar-scroll">
            <nav id="leftsidebar-nav" class="sidebar-nav">
                <ul id="main-menu" class="metismenu">

                    <li class="active"><a href="{% url 'StudentPanel:home' %}"><i class="icon-home"></i><span>Dashboard</span></a></li>
                    <li class="heading">Main</li>


                    {% if request.user.last_name == "I_Student" %}

                    <li>
                        <a href="{% url 'StudentPanel:courses' %}" class="has-arrow"><i class="fa fa-folder"></i>
                        	<span>Your Courses</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'StudentPanel:FeeDetails' %}" class="has-arrow"><i class="fa fa-money"></i>
                        	<span>Fee Details</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'StudentPanel:student_notification' %}" class="has-arrow"><i class="fa fa-bell"></i>
                        	<span>Notification</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'StudentPanel:student_ecorner' %}" class="has-arrow"><i class="fa fa-tag"></i>
                        	<span>E-Corner</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'StudentPanel:issue_return_book' %}" class="has-arrow"><i class="fa fa-book"></i>
                        	<span>Issued-Retuned Book</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'StudentPanel:student_upload_document' %}" class="has-arrow"><i class="fa fa-download"></i><span>Upload Section</span></a>

                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>






    {% block body %}
    {% endblock %}


</div>

<!-- Javascript -->
<script src="{% static 'student/assets/bundles/libscripts.bundle.js' %}"></script>
<script src="{% static 'student/assets/bundles/vendorscripts.bundle.js' %}"></script>

<script src="{% static 'student/assets/bundles/chartist.bundle.js' %}"></script>
<script src="{% static 'student/assets/bundles/knob.bundle.js' %}"></script> <!-- Jquery Knob-->
<script src="{% static 'student/assets/bundles/flotscripts.bundle.js' %}"></script> <!-- flot charts Plugin Js -->
<script src="{% static 'student/assets1/vendor/flot-charts/jquery.flot.selection.js' %}"></script>

<script src="{% static 'student/assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'student/assets/js/index.js' %}"></script>


<script>

    $('.knob').knob({
        draw: function() {
            // "tron" case
            if (this.$.data('skin') == 'tron') {

                var a = this.angle(this.cv) // Angle
                    ,
                    sa = this.startAngle // Previous start angle
                    ,
                    sat = this.startAngle // Start angle
                    ,
                    ea // Previous end angle
                    , eat = sat + a // End angle
                    ,
                    r = true;

                this.g.lineWidth = this.lineWidth;

                this.o.cursor &&
                    (sat = eat - 0.3) &&
                    (eat = eat + 0.3);

                if (this.o.displayPrevious) {
                    ea = this.startAngle + this.angle(this.value);
                    this.o.cursor &&
                        (sa = ea - 0.3) &&
                        (ea = ea + 0.3);
                    this.g.beginPath();
                    this.g.strokeStyle = this.previousColor;
                    this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false);
                    this.g.stroke();
                }

                this.g.beginPath();
                this.g.strokeStyle = r ? this.o.fgColor : this.fgColor;
                this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false);
                this.g.stroke();

                this.g.lineWidth = 2;
                this.g.beginPath();
                this.g.strokeStyle = this.o.fgColor;
                this.g.arc(this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false);
                this.g.stroke();

                return false;
            }
        }
    });

     $('#linecustom1').sparkline('html',{
        height: '55px',
        width: '100%',
        lineColor: '#a095e5',
        fillColor: '#a095e5',
        minSpotColor: true,
        maxSpotColor: true,
        spotColor: '#e2a8df',
        spotRadius: 0
    });

    $('#linecustom2').sparkline('html',{
        height: '55px',
        width: '100%',
        lineColor: '#75c3f2',
        fillColor: '#75c3f2',
        minSpotColor: true,
        maxSpotColor: true,
        spotColor: '#8dbfe0',
        spotRadius: 0
    });

    $('#linecustom3').sparkline('html',{
        height: '55px',
        width: '100%',
        lineColor: '#fc7b92',
        fillColor: '#fc7b92',
        minSpotColor: true,
        maxSpotColor: true,
        spotColor: '#e0b89d',
        spotRadius: 0
    });
</script>


</body>
</html>

<!-- Localized -->