Student/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "StudentPanel"
urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^$', Dashboard, name = 'home'),
url(r'^Add_link/(?P<option>[\w-]+)/$', Students_Link_add, name = 'students_links'),
url(r'^profile/$', Student_profile, name = 'profile'),
url(r'^Change_password/$', Chenge_password, name = 'change_password'),
url(r'^Edit_profile/$', Student_edit_profile, name = 'edit_profile'),
url(r'^test_list/$', AllTests, name = 'tests'),
url(r'^exams_list/(?P<pid>[\w-]+)/$', All_Exams, name = 'exams'),
url(r'^Generate_invoice/(?P<pid>[0-9]+)/$', Student_generate_invoice, name = 'invoice'),




url(r'^test_instruction/(?P<eid>[\w-]+)/$', TestInstruction, name = 'instruction'),
url(r'^test_live/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', LiveTest, name = 'live'),
url(r'^analysis/(?P<eid>[\w-]+)/$', TestAnalysis, name = 'analysis'),
url(r'^Exam_Solution/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', ExamSolution, name = 'solution'),



url(r'^practice/$', Practice, name = 'practice'),
url(r'^practice_questions/$', PracticeQuestion, name = 'practice_questions'),
url(r'^single_question/$', StartPractice, name = 'single_question'),

url(r'^quiz/$', AllQuiz, name = 'quiz'),
url(r'^start_quiz/(?P<qid>[\w-]+)/(?P<q_id>[\w-]+)/(?P<time>[\w-]+)/$', StartQuiz, name = 'start_quiz'),
url(r'^quiz_summery/(?P<qid>[\w-]+)/analysis_Answers/$', QuizSummery, name = 'quiz_summery'),
url(r'^quiz_solution/(?P<qid>[\w-]+)/Answers/(?P<q_id>[\w-]+)/$', QuizSolution, name = 'quiz_solution'),



url(r'^study_material/$', Study_Material, name = 'study_material'),
url(r'^courses/$', Courses, name = 'courses'),
url(r'^fee/$', FeeDetails, name = 'FeeDetails'),
url(r'^invoice/$', Invoice, name = 'invoice'),

url(r'^Installment_details/(?P<cid>[0-9]+)/$', FeeInstallmentDetails, name = 'installment_details'),
url(r'^Notifications/$', Student_Notifications, name = 'student_notification'),
url(r'^Uploaded_Document/$', Student_Upload_Documents, name = 'student_upload_document'),
url(r'^E_corner/$', Student_Ecorner, name = 'student_ecorner'),
url(r'^Issued_Returned_Book/$', Student_issued_returned_book, name = 'issue_return_book'),


]

WebSite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from WebSite.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "Website"
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^$', Website_home,name='website_home'),
    url(r'^About_us/$', AboutUs, name='aboutus'),
url(r'^Contact_us/$', ContactUs, name='contact'),
url(r'^Branches/$', Branches, name='branches'),
url(r'^Student_Zone/$', Student_Zone, name='student_zone'),
url(r'^Student_Reviews/$', Student_Reviews, name='student_review'),
url(r'^Student_Query/$', Student_quiry_form, name='student_query'),
url(r'^login/$', Website_admin_login,name='web_login'),
url(r'^logout/$', Website_admin_logout,name='web_logout'),
url(r'^add_slider/$', Website_slider_add,name='web_slider'),
url(r'^delete_slider/(?P<sid>[0-9]+)/$', Website_slider_delete,name='delete_slider'),
url(r'^Add_sub_course/(?P<mid>[0-9]+)/$', Website_add_subcourse,name='web_add_subcourse'),
url(r'^Course_details/(?P<mid>[0-9]+)/$', Main_course_details,name='main_cdetails'),
url(r'^subCourse_details/(?P<sid>[0-9]+)/$', Sub_course_details,name='sub_cdetails'),
url(r'^Chenge_profile/(?P<type>[\w-]+)/$', Change_profile,name='change_profile'),
url(r'^Chenge_Content/(?P<type>[\w-]+)/$', Edit_Welcome_content,name='edit_content'),
url(r'^Chenge_about_content/(?P<type>[\w-]+)/$', Edit_About_Content,name='edit_about_content'),
url(r'^change_image/(?P<option>[\w-]+)/$', Change_image,name='change_image'),
url(r'^Delete_course/(?P<type>[\w-]+)/(?P<num>[0-9]+)$', Delete_stuff,name='delete_stuff'),
url(r'^Edit_course/(?P<num>[0-9]+)$', Edit_Main_course,name='edit_maincourse'),
url(r'^add_course/$', Website_add_course,name='web_add_course'),
url(r'^add_review/$', Add_Review,name='add_review'),
url(r'^add_faculty_review/$', Add_Faculty_Review,name='add_f_review'),
url(r'^add_brand/$', Add_brand,name='add_brand'),
url(r'^Our_Gallery/$', Our_gallery,name='our_gallery'),
url(r'Add_Gallery/$', Add_Gallery,name='add_gallery'),
url(r'^Edit_counter_value/$', Edit_counter,name='edit_counter'),
url(r'^Edit_Subcourse/(?P<type>[\w-]+)/(?P<num>[0-9]+)$', Edit_sub_course,name='edit_subcourse'),
url(r'^Edit_Content/(?P<num>[0-9]+)/$', Edit_course_content,name='edit_course_content'),
url(r'^Add_content/(?P<num>[0-9]+)/$', Add_content,name='add_content'),
url(r'^Add_Sub_course/(?P<num>[0-9]+)/$', Add_sub_course,name='add_sub_course'),



]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Institute.views import *
from django.conf import settings
from django.conf.urls.static import static
from WebSite.views import *


urlpatterns = [
    url(r'^register/$', Register, name = "register"),
    url(r'^forgot_password/$', ForgotPass, name = "Forgot"),
    url(r'^login/$', Login, name = "login"),
    url(r'^$', Website_home, name = "website_home"),
    url(r'^SkyLark/$', Start, name = "demo"),
    url(r'^logout$', Logout, name = "logout"),
    url(r'^frontdesk/', include('Frontdesk.urls', namespace='Frontdesk')),
    url(r'^Student_panel/', include('Student.urls', namespace='StudentPanel')),
    url(r'^website/', include('WebSite.urls', namespace='Website')),

    url(r'^exam_controller/', include('ExamPanel.urls', namespace='ExamPanel')),
    url(r'^library_panel/', include('LibraryPanel.urls', namespace='LibraryPanel')),
    url(r'^master_panel/', include('Institute.urls', namespace='Master')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebSite/models.py
from django.db import models
from Institute.models import *
# Create your models here.

class Banner(models.Model):
    slider = models.FileField(null=True,blank=True)
    head = models.CharField(max_length=100,null=True,blank=True)
    subhead = models.CharField(max_length=200,null=True,blank=True)


class Main_course(models.Model):
    name = models.CharField(max_length=100,null=True,blank=True)
    dis = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.name

class Sub_course(models.Model):
    main_course = models.ForeignKey(Main_course,models.CASCADE,null=True)
    name = models.CharField(max_length=100,null=True,blank=True)
    image = models.FileField(null=True, blank=True)
    dis = models.CharField(max_length=200, null=True, blank=True)
    long_dis = models.CharField(max_length=2000, null=True, blank=True)
    fee = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.main_course.name + ' -> ' + self.name

class Course_content(models.Model):
    sub_course = models.ForeignKey(Sub_course, models.CASCADE, null=True)
    heading = models.CharField(max_length=200,null=True,blank=True)
    content = models.TextField(null=True,blank=True)


class Student_Feedback(models.Model):
    sub_course = models.ForeignKey(Sub_course,on_delete=models.CASCADE,null=True)
    image = models.FileField(null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)

class Student_Query(models.Model):
    institute = models.ForeignKey(Institite_profile,on_delete=models.CASCADE,null=True)
    course = models.ForeignKey(Sub_course,on_delete=models.CASCADE,null=True)
    name =  models.CharField(max_length=100, null=True, blank=True)
    mobile = models.CharField(max_length=13, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    message = models.TextField(null=True, blank=True)


class Director_Profile(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    mobile_number = models.CharField(max_length=10, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    director_message = models.TextField(null=True, blank=True)


class Welcome_content(models.Model):
    image = models.FileField(null=True, blank=True)
    content = models.TextField(null=True,blank=True)
    why_choose = models.TextField(null=True,blank=True)

class About_Us_content(models.Model):
    who_we_are = models.TextField(null=True,blank=True)
    image1 = models.FileField(null=True, blank=True)
    why_join_us = models.TextField(null=True,blank=True)
    image2 = models.FileField(null=True, blank=True)
    our_vision = models.TextField(null=True,blank=True)
    our_mission = models.TextField(null=True,blank=True)
    mission_tag_line = models.CharField(max_length=100, null=True, blank=True)

class Counter_data(models.Model):
    value1 = models.IntegerField(null=True, blank=True)
    value2 = models.IntegerField(null=True, blank=True)
    value3 = models.IntegerField(null=True, blank=True)
    value4 = models.IntegerField(null=True, blank=True)



class Brands(models.Model):
    image = models.FileField(null=True, blank=True)

class Faculty_Feddback(models.Model):
    image = models.FileField(null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)


class Our_gallery_data(models.Model):
    image = models.FileField(null=True)
    Title = models.CharField(max_length=100,null=True)

WebSite/templates/web/about_us.html
{% extends 'web/base.html' %}
{% load static %}
{% block body %}    <!-- slider-start -->
    <div class="slider-area" >
        <div class="page-title">
            <div class="single-slider   d-flex align-items-center" style="background-image: url('{% static 'web/img/bg/others_bg.jpg' %}');height:200px;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider-content slider-content-breadcrumb text-center">
                                <h2 class="white-color f-700">About Us</h2>
                                <nav class="text-center" aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center">
                                        <li class="breadcrumb-item"><a href="{% url 'Website:website_home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">About Us</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider-end -->
    <!-- about start -->
    <div id="about" class="about-area pt-100 pb-70">

        <div class="container">


            <div class="row">
                <div class="col-xl-7 col-lg-7">
                   <h2 style="font-family:monospace;">About <span style="color:#e1261f;">Sankalp</span> Institute</h2>
                    <div class="about-title-section about-title-section-2 mb-30">
                        <h4 style="color:#eeaf0a;font-family:cursive"><b><u>Who We Are</u></b>
                        {% if request.user.is_staff %}
                            <a href="{% url 'Website:edit_about_content' 'Who_we_are' %}"><span class="ti-pencil"></span></a>
                        {% endif %}
                        </h4>
                        <p>{{ about_content.who_we_are }}</p></div>
                </div>
                <div class="col-xl-5 col-lg-5">
                    <div class="about-img mb-55">
                        {% if request.user.is_staff %}
                        <a href="{% url 'Website:change_image' 'Who_we_are' %}"><img src="{{ about_content.image1.url }}" alt=""></a>
                        {% else %}
                        <img src="{{ about_content.image1.url }}" alt="">
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>

            <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5">
                    <div class="about-img mb-55">
                        {% if request.user.is_staff %}
                        <a href="{% url 'Website:change_image' 'Why_join_us' %}"><img src="{{ about_content.image2.url }}" alt=""></a>
                        {% else %}
                        <img src="{{ about_content.image2.url }}" alt="">
                        {% endif %}
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7">
                    <div class="about-title-section about-title-section-2 mb-30">
                        <h4 style="color:#eeaf0a;font-family:cursive"><b><u>Why To Join Sankalp ?</u></b>
                        {% if request.user.is_staff %}
                            <a href="{% url 'Website:edit_about_content' 'Why_join_us' %}"><span class="ti-pencil"></span></a>
                        {% endif %}
                        </h4>
                        <p>{{ about_content.why_join_us }}</p></div>
                </div>

            </div>

        </div>

            <div class="container">
            <div class="row">

                <div class="col-xl-12 col-lg-12">
                    <div class="about-title-section about-title-section-2 mb-30">
                        <h4 style="color:#eeaf0a;font-family:cursive"><b><u>Our Vision</u></b>
                       {% if request.user.is_staff %}
                            <a href="{% url 'Website:edit_about_content' 'Our_vision' %}"><span class="ti-pencil"></span></a>
                        {% endif %} 
                        </h4>
                    <p>{{ about_content.our_vision }}</p>

                    </div>
                </div>

            </div>
                <div class="row">

                <div class="col-xl-12 col-lg-12">
                    <div class="about-title-section about-title-section-2 mb-30">
                        <h4 style="color:#eeaf0a;font-family:cursive"><b><u>Our Mission</u></b>
                        {% if request.user.is_staff %}
                            <a href="{% url 'Website:edit_about_content' 'Our_mission' %}"><span class="ti-pencil"></span></a>
                        {% endif %}
                        </h4>
                        <span> <b>{{ about_content.mission_tag_line }}{% if request.user.is_staff %}
                            <a href="{% url 'Website:edit_about_content' 'Mission_tag_line' %}"><span class="ti-pencil"></span></a>
                        {% endif %}</b></span>
                        <p> {{ about_content.our_mission }}</p></div>
                </div>

            </div>

        </div>
        <div class="container">

            <div class="row">


                <div class="col-xl-12">
                    <h2 style="font-family:monospace;"><span style="color:#e1261f;">Director's Message</span> </h2>



                                        <div class="author-comments-box d-flex">

                                            <div class="author-comments-avatar">
                                                <img src="{{ profile.image.url }}" alt="" height="100px;" width="100px;">
                                            </div>
                                            <div class="author-comments-text">
                                                <div class="author-comments-title">
                                                    <h5>{{ profile.name }}</h5>
                                                    <h6>Director</h6>
                                                </div>
                                                <p>{{ profile.director_message }}</p>
                                                <p>Thank you for considering us as the best coaching Institute for your child.</p>
                    <p>With best regards</p>
                    <p><b>Mob.: {{ profile.mobile_number }}<br>
                            Email: {{ profile.email }}</b></p>
                                                </div>
                                        </div>
                                    </div>

            </div>

        </div>
    </div>
    <!-- about end -->

   {% endblock %}

WebSite/templates/web/branches.html
{% extends 'web/base.html' %}
{% load static %}
{% block body %}
    <!-- slider-start -->

    <div class="slider-area">
        <div class="page-title">
            <div class="single-slider   d-flex align-items-center" style="background-image: url('{% static 'web/img/bg/others_bg.jpg' %}');height:200px;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider-content slider-content-breadcrumb text-center">
                                <h2 class="white-color f-700">Our Branches</h2>
                                <nav class="text-center" aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center">
                                        <li class="breadcrumb-item"><a href="{% url 'Website:website_home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Branches</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider-end -->
    <!-- courses start -->
   <div class="events-area gray-bg pt-100 pb-70">
        <div class="container">
            <div class="events-list">
                <div class="row">
                    {% for i in all_branch %}
                    <div class="col-xl-6 offset-xl-0 col-lg-6 offset-lg-0 col-md-10 offset-md-1">
                        <div class="single-events mb-30">
                            <div class="events-wrapper events-wrapper-padding">
                                <div class="events-inner d-flex">

                                    <div class="events-text white-bg">
                                        <div class="event-text-heading mb-20">
                                            <div class="events-calendar text-center f-left">
                                                <a href=""><img src="{{ i.institute_logo.url }}" alt="" height="50px;" width="50px;"></a>

                                            </div>
                                            <div class="events-text-title clearfix">
                                                <a href="">
                                                    <h4>{{ i.Title }}</h4>
                                                </a>
                                                <div class="time-area">

                                                    <span class="published-time">{{ i.sub_title }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="events-para">
                                            <p><b>Email: </b>{{ i.email }}</p>
                                             <p><b>Address: </b>{{ i.office_add }}</p>
                                             <p><b>Mobile Number: </b>{{ i.office_mob }}</p>
                                        </div>
                                        <div class="events-speaker">
                                            <h2>Website : <span><a href="{{ i.website }}" target="_blank">{{ i.website }}</a></span></h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div></div></div></div>
    <!-- courses end -->

    {% endblock %}

WebSite/templates/web/main_course_details.html
{% extends 'web/base.html' %}
{% load static %}
{% block body %}
    <!-- slider-start -->

    <div class="slider-area">
        <div class="page-title">
            <div class="single-slider   d-flex align-items-center" style="background-image: url('{% static 'web/img/bg/others_bg.jpg' %}');height:200px;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider-content slider-content-breadcrumb text-center">
                                <h2 class="white-color f-700">{{ data.name }}</h2>
                                <nav class="text-center" aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center">
                                        <li class="breadcrumb-item"><a href="{% url 'Website:website_home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">{{ data.name }} Details</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider-end -->
    <!-- courses start -->
    <div class="advisors-area gray-bg pt-20 pb-70" style="background-image: url('{% static 'web/sbg.png' %}')">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="section-title mb-50 text-center">
                        <div class="section-title-heading mb-20">
                            <h2 class="primary-color">All Sub Courses for {{ data.name }}</h2>
                            {% if request.user.is_staff %}
                            <div class="courses-pricing-3">
                                <br>
                                <a href="{% url 'Website:add_sub_course' data.id %}"><span>Add More Course</span></a>
                                    </div>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                {% for i in data.sub_course_set.all %}
                     <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="skill-style">
                        <div class="img-box">
                            <div class="text-box text-center">
                                <a href="{% url 'Website:sub_cdetails' i.id %}"><div class="inner hvr-bounce-to-bottom" style="min-height: 230px;">
                                    <div class="icon-box">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                    </div><!-- /.icon-box -->
                                    <a href="{% url 'Website:sub_cdetails' i.id %}"><h3>{{ i.name }}</h3></a>
                                    <p>{{ i.dis }}</p>
                                    <a href="{% url 'Website:sub_cdetails' i.id %}" class="more">Read More </a>
                                </div><!-- /.inner --></a>
                            </div><!-- /.text-box -->
                        </div><!-- /.img-box -->
                    </div><!-- /.single-service-style-three -->
                </div>{% endfor %}
            </div>
        </div>
    </div>
    <!-- courses end -->

    {% endblock %}

WebSite/templates/web/student_review.html
{% extends 'web/base.html' %}
{% load static %}
{% block body %}    <!-- slider-start -->
    <div class="slider-area" >
        <div class="page-title">
            <div class="single-slider   d-flex align-items-center" style="background-image: url('{% static 'web/img/bg/others_bg.jpg' %}');height:200px;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider-content slider-content-breadcrumb text-center">
                                <h2 class="white-color f-700">Student's Review</h2>
                                <nav class="text-center" aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center">
                                        <li class="breadcrumb-item"><a href="{% url 'Website:website_home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Student's Review</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider-end -->
     <!-- testimonials start -->
    <div class="testimonilas-area pt-10 pb-90" style="background-image: url('{% static 'web/sbg.png' %}')">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="section-title mb-50 text-center">
                        <div class="section-title-heading mb-20">
                            <h1 class="primary-color">What Our Students Say</h1>
                            {% if request.user.is_staff %}
                            <a href="{% url 'Website:add_review' %}"><span class="btn-text">Add Reviews</span></a>
                           {% endif %}
                        </div>
                        <div class="section-title-para">
                            <p class="gray-color">The Sankalp Institutes is entirely committed towards the education of students.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="testimonilas-list">
                <div class="row testimonilas-active">


                    {% for i in all_feedback %}
                    <div class="col-xl-12">
                        <div class="testimonilas-wrapper">
                            <div class="testimonilas-heading d-flex">
                                <div class="testimonilas-author-thumb">
                                    <img src="{{ i.image.url }}" alt="" height="50px;" width="50px;">
                                </div>
                                <div class="testimonilas-author-title">
                                    <h1>{{ i.name }}</h1>
                                    <h2>{{ i.sub_course.name }}</h2>
                                </div>
                            </div>
                            <div class="testimonilas-para">
                                <p>{{ i.feedback }}
                                    {% if request.user.is_staff %}
                                <a href="{% url 'Website:delete_stuff' 'Review' i.id %}"><span class="ti-trash" style="font-size:20px;"></span></a></li>
                                {% endif %}
                                </p>
                            </div>

                        </div>
                    </div> {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <!-- testimonials end -->

   {% endblock %}

WebSite/templates/web/student_zone.html
{% extends 'web/base.html' %}
{% load static %}
{% block body %}
    <!-- slider-start -->

    <div class="slider-area">
        <div class="page-title">
            <div class="single-slider   d-flex align-items-center" style="background-image: url('{% static 'web/img/bg/others_bg.jpg' %}');height:200px;">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="slider-content slider-content-breadcrumb text-center">
                                <h2 class="white-color f-700">Batches Details</h2>
                                <nav class="text-center" aria-label="breadcrumb">
                                    <ol class="breadcrumb justify-content-center">
                                        <li class="breadcrumb-item"><a href="{% url 'Website:website_home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">New Batch</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider-end -->
    <!-- courses start -->
   <div class="events-area white-bg pt-100 pb-70">
        <div class="container">
            <div class="events-list">
                <center><h3 style="color:#1A2E6E;font-family:monospace;">All <span style="color:orange"><b>Upcoming Batches</b></span> For All Center.</h3>
                 </center><div class="row">
                     {% for i in institutes %}
                    {% if i.id in ids %}
                                    <div class="col-xl-6">
                                        <div class="author-comments-box d-flex">
                                            <div class="author-comments-avatar">
                                                <img src="{{ i.institute_logo.url }}" alt="" height="80px;" width="80px;">
                                            </div>
                                            <div class="author-comments-text">
                                                <div class="author-comments-title">
                                                    <h5>{{ i.Title }}</h5>
                                                    <span>{{ i.sub_title }}</span>
                                                </div>
                                                {% for j in upcoming_batch %}
                                                {% if i.id == j.ins.id %}
                                                <p style="color:black"><i class="ti-star" style="color:orange"></i> <b>{{ j.name }}</b> Start Date: <b>{{ j.start_date }}</b></p>
                                                 {% endif %}
                                                 {% endfor %}
                                             </div>
                                        </div>

                                    </div>
                     {% endif %}
                    {% endfor %}


                                </div>
                            </div>
            </div></div>
    <!-- courses end -->

    {% endblock %}