LibraryPanel/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "LibraryPanel"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Library_Deshboard,name = 'library_deshboard'),
    url(r'^Add_category/$', Library_Add_Category,name = 'Library_add_cat'),
    url(r'^Book_List/(?P<opt>[\w-]+)/$', Library_Book_List,name = 'Library_book_List'),
    url(r'^Add_Book_Sub_Category/$', Library_add_sub_category,name = 'Library_add_sub_cat'),
    url(r'^Library_add_books/(?P<cat>[\w-]+)/$', Library_Add_Books,name = 'Library_add_books'),
    url(r'^Library_books_Details/(?P<bid>[0-9]+)/$', Library_book_details,name = 'Library_book_details'),
    url(r'^Library_books_Edit_Details/(?P<bid>[0-9]+)/(?P<cat>[0-9]+)/(?P<subcat>[0-9]+)$', Library_Book_Edit_Details,name = 'Library_book_edit'),
    url(r'^Library_online_books/$', Library_Online_Book, name = 'Library_online_book'),
    url(r'^Library_e_books_Edit_Details/(?P<bid>[0-9]+)/(?P<cat>[0-9]+)/(?P<subcat>[0-9]+)$', Library_E_Book_Edit_Details,
        name='Library_e_book_edit'),

    url(r'^Library_add_e_books/(?P<cat>[\w-]+)/$', Library_E_Add_Books, name='Library_add_e_books'),
    url(r'^Library_delete_e_book/(?P<bid>[0-9]+)/$', Library_Online_Delete_Book, name='Library_delete_book'),

    url(r'^Library_issue_books/(?P<student_data>[\w-]+)/(?P<bid>[0-9]+)/$', Library_Book_Issue, name = 'Library_issue_book'),
    url(r'^Filter_rollNumber/$', Filter_RollNumber, name='filter_roll_number'),

    url(r'^Library_issued_books/$', Library_Issued_Books, name = 'Library_issued_book'),
    url(r'^Library_Return_Book/(?P<bid>[0-9]+)/$', Library_Return_Book,name = 'Library_Return_Book'),
    url(r'^Library_Return_Book_list/$', Issue_Book_Return,name = 'Library_Return_Book_list'),
    url(r'^Stuednt_library_fine_list/$', Library_Student_Fine_List,name = 'Library_fine_list'),
    url(r'^Delete/(?P<num>[0-9]+)/(?P<type>[\w-]+)/$', Delete_for_all,
        name='delete_for_all'),
    url(r'^UnCategorized_books/$', Uncategorized_books, name='un_cat_book'),
    url(r'^Asign_catagory/(?P<cate>[0-9]+)/(?P<bid>[0-9]+)/$', Asign_category_to_book, name='asign_cat'),


]

Student/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "StudentPanel"
urlpatterns = [
url(r'^admin/', admin.site.urls),
url(r'^$', Dashboard, name = 'home'),
url(r'^Add_link/(?P<option>[\w-]+)/$', Students_Link_add, name = 'students_links'),
url(r'^profile/$', Student_profile, name = 'profile'),
url(r'^Change_password/$', Chenge_password, name = 'change_password'),
url(r'^Edit_profile/$', Student_edit_profile, name = 'edit_profile'),
url(r'^test_list/$', AllTests, name = 'tests'),
url(r'^exams_list/(?P<pid>[\w-]+)/$', All_Exams, name = 'exams'),
url(r'^Generate_invoice/(?P<pid>[0-9]+)/$', Student_generate_invoice, name = 'invoice'),




url(r'^test_instruction/(?P<eid>[\w-]+)/$', TestInstruction, name = 'instruction'),
url(r'^test_live/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', LiveTest, name = 'live'),
url(r'^analysis/(?P<eid>[\w-]+)/$', TestAnalysis, name = 'analysis'),
url(r'^Exam_Solution/exam/(?P<eid>[\w-]+)/section/(?P<sid>[\w-]+)/question/(?P<qid>[\w-]+)/(?P<num>[\w-]+)/(?P<what>[\w-]+)/(?P<time>[\w-]+)/$', ExamSolution, name = 'solution'),



url(r'^practice/$', Practice, name = 'practice'),
url(r'^practice_questions/$', PracticeQuestion, name = 'practice_questions'),
url(r'^single_question/$', StartPractice, name = 'single_question'),

url(r'^quiz/$', AllQuiz, name = 'quiz'),
url(r'^start_quiz/(?P<qid>[\w-]+)/(?P<q_id>[\w-]+)/(?P<time>[\w-]+)/$', StartQuiz, name = 'start_quiz'),
url(r'^quiz_summery/(?P<qid>[\w-]+)/analysis_Answers/$', QuizSummery, name = 'quiz_summery'),
url(r'^quiz_solution/(?P<qid>[\w-]+)/Answers/(?P<q_id>[\w-]+)/$', QuizSolution, name = 'quiz_solution'),



url(r'^study_material/$', Study_Material, name = 'study_material'),
url(r'^courses/$', Courses, name = 'courses'),
url(r'^fee/$', FeeDetails, name = 'FeeDetails'),
url(r'^invoice/$', Invoice, name = 'invoice'),

url(r'^Installment_details/(?P<cid>[0-9]+)/$', FeeInstallmentDetails, name = 'installment_details'),
url(r'^Notifications/$', Student_Notifications, name = 'student_notification'),
url(r'^Uploaded_Document/$', Student_Upload_Documents, name = 'student_upload_document'),
url(r'^E_corner/$', Student_Ecorner, name = 'student_ecorner'),
url(r'^Issued_Returned_Book/$', Student_issued_returned_book, name = 'issue_return_book'),


]

django_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Institute.views import *
from django.conf import settings
from django.conf.urls.static import static
from WebSite.views import *


urlpatterns = [
    url(r'^register/$', Register, name = "register"),
    url(r'^forgot_password/$', ForgotPass, name = "Forgot"),
    url(r'^login/$', Login, name = "login"),
    url(r'^$', Website_home, name = "website_home"),
    url(r'^SkyLark/$', Start, name = "demo"),
    url(r'^logout$', Logout, name = "logout"),
    url(r'^frontdesk/', include('Frontdesk.urls', namespace='Frontdesk')),
    url(r'^Student_panel/', include('Student.urls', namespace='StudentPanel')),
    url(r'^website/', include('WebSite.urls', namespace='Website')),

    url(r'^exam_controller/', include('ExamPanel.urls', namespace='ExamPanel')),
    url(r'^library_panel/', include('LibraryPanel.urls', namespace='LibraryPanel')),
    url(r'^master_panel/', include('Institute.urls', namespace='Master')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LibraryPanel/models.py
from __future__ import unicode_literals

from django.db import models
from Frontdesk.models import *
from Institute.models import *
# Create your models here.
class Master_catbook_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    created_date = models.CharField(max_length=20, null=True, blank=True)


    def __str__(self):
        return self.name

class Master_subcatbook_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Master_catbook_data,models.CASCADE,null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    created_date = models.CharField(max_length=20, null=True, blank=True)


    def __str__(self):
        return self.name

class Master_book_data(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True,blank=True)
    cover_image = models.FileField(null=True,blank=True)
    category = models.ForeignKey(Master_catbook_data,on_delete=models.SET_NULL,null=True, blank=True)
    subcategory = models.ForeignKey(Master_subcatbook_data,on_delete=models.SET_NULL,null=True, blank=True)
    book_title = models.CharField(max_length=100, null=True, blank=True)
    subbook_title = models.CharField(max_length=100, null=True, blank=True)
    ISBN = models.CharField(max_length=100, null=True, blank=True)
    author = models.CharField(max_length=100, null=True, blank=True)
    publisher = models.CharField(max_length=100, null=True, blank=True)
    editor = models.CharField(max_length=100, null=True, blank=True)
    series = models.CharField(max_length=100, null=True, blank=True)
    publication_year = models.CharField(max_length=100, null=True, blank=True)
    edition = models.CharField(max_length=100, null=True, blank=True)
    pages = models.CharField(max_length=100, null=True, blank=True)
    copies = models.CharField(max_length=100, null=True, blank=True)
    ave_copy = models.CharField(max_length=100, null=True, blank=True)
    created_date = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.book_title

class Master_E_Book(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Master_catbook_data,on_delete= models.SET_NULL, null=True, blank=True)
    subcategory = models.ForeignKey(Master_subcatbook_data, on_delete=models.SET_NULL, null=True, blank=True)
    book_title = models.CharField(max_length=100, null=True, blank=True)
    author = models.CharField(max_length=100, null=True, blank=True)
    publisher = models.CharField(max_length=100, null=True, blank=True)
    book = models.FileField(null=True, blank=True)
    created_date = models.CharField(max_length=100, null=True, blank=True)




class Library_Issue_Book(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Master_book_data, on_delete=models.CASCADE)
    student = models.ForeignKey(Front_student_data, on_delete=models.CASCADE)
    issue = models.CharField(max_length=50, null=True, blank=True)
    Due = models.CharField(max_length=50, blank=True, null=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    Return = models.CharField(max_length=50, null=True, blank=True)
    late_fee = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.student.name + " / " + self.book.book_title




class LateFine(models.Model):
    ins = models.ForeignKey(Institite_profile, on_delete=models.CASCADE, null=True)
    libraryfine = models.CharField(max_length=20, null=True, blank=True)
    latefeefine = models.CharField(max_length=20, null=True, blank=True)

LibraryPanel/forms.py
from .models import *
from django import forms


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Master_book_data
        exclude = ('category','subcategory','created_date', 'ave_copy','ins')
        widgets = {
            "cover_image": forms.FileInput(attrs={ 'class': 'form-control'
                                                 }),
            "book_title": forms.TextInput(attrs={'placeholder': 'Book Title','class': 'form-control', "required": '',
                                             }),
            "subbook_title": forms.TextInput(attrs={'placeholder': 'Sub Title',
                                            'class': 'form-control', "required": ''}),
            "ISBN": forms.TextInput(attrs={'placeholder': 'ISBN',
                                         'class': 'form-control'}),
            "author": forms.TextInput(attrs={'placeholder': 'Author Name', 'class': 'form-control',
                                                 }),
            "publisher": forms.TextInput(attrs={'placeholder': 'Publisher Name',
                                                    'class': 'form-control'}),
            "editor": forms.TextInput(attrs={'placeholder': 'Editor Name',
                                          'class': 'form-control'}),
            "series": forms.TextInput(attrs={'placeholder': 'Series', 'class': 'form-control'
                                                 }),
            "publication_year": forms.TextInput(attrs={'placeholder': 'Publication Year',
                                                    'class': 'form-control'}),
            "edition": forms.TextInput(attrs={'placeholder': 'Edition',
                                          'class': 'form-control'}),
            "pages": forms.TextInput(attrs={'placeholder': 'Number Of Pages',
                                                    'class': 'form-control'}),
            "copies": forms.TextInput(attrs={'placeholder': 'Number Of Copies',
                                          'class': 'form-control', "required": ''}),

        }

class AddEbookForm(forms.ModelForm):
    class Meta:
        model = Master_E_Book
        exclude = ('category','subcategory','created_date','ins')
        widgets = {

            "book_title": forms.TextInput(attrs={'placeholder': 'Book Title','class': 'form-control', "required": '',
                                             }),

            "author": forms.TextInput(attrs={'placeholder': 'Author Nmae', 'class': 'form-control',
                                                 }),
            "publisher": forms.TextInput(attrs={'placeholder': 'Publisher Name',
                                                    'class': 'form-control',}),

            "book": forms.FileInput(attrs={'class': 'form-control', "required": ''}),

        }

LibraryPanel/templates/Library/library_deshboard.html
{% extends 'Library/base.html' %}

{% block up %}


<!doctype html>
<html class="no-js " lang="en">

<!-- Mirrored from thememakker.com/templates/oreo/university/html/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 17 Sep 2018 02:52:22 GMT -->
<head>
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">

<title>{{ ins_data.name }} - Library Dashboard</title>
<!-- Favicon-->
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
<!-- Custom Css -->
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
</head>
{% endblock %}

{% block down %}

<!-- Main Content -->
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Library Desboard
                <small>Welcome to Library panel</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">

                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href=""><i class="zmdi zmdi-home"></i> Deshboard</a></li>
                    </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
           <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <ul class="row profile_state list-unstyled">
                        <li class="col-lg-3 col-md-3 col-6">
                            <a href="{% url 'LibraryPanel:Library_book_List' 'All' %}">
                            <div class="body">
                                <i class="zmdi zmdi-book-image col-teal"></i>
                                <h4>{{ total_book }}</h4>
                                <span>Total Books</span>
                            </div>
                            </a>
                        </li>
                        <li class="col-lg-3 col-md-3 col-6">
                            <a href="{% url 'LibraryPanel:Library_online_book' %}">
                            <div class="body">
                                <i class="zmdi zmdi-book col-red"></i>
                                <h4>{{ total_ebook }}</h4>
                                <span>Total E-Books</span>
                            </div>
                            </a>
                        </li>
                        <li class="col-lg-3 col-md-3 col-6">
                            <a href="{% url 'LibraryPanel:un_cat_book' %}">
                            <div class="body">
                                <i class="zmdi zmdi-copy col-blue"></i>
                                <h4>{{ all_un_cat_book }}</h4>
                                <span>Un-categorized Books</span>
                            </div>
                            </a>
                        </li>
                        <li class="col-lg-3 col-md-3 col-6">
                            <a href="{% url 'LibraryPanel:Library_issued_book' %}">
                            <div class="body">
                                <i class="zmdi zmdi-tab text-primary"></i>
                                <h4>{{ all_issued_book.count }}</h4>
                                <span>Total Issued Books</span>

                            </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row clearfix">
                <div class="col-sm-12 col-md-12 col-lg-6">
                <div class="card">
                    <div class="header">
                        <h2><strong>Last </strong>Issued Book</h2>

                    </div>
                    <div class="body">
                        <ul class="inbox-widget list-unstyled clearfix">
                            {% for i in last_five %}
                            <li class="inbox-inner">
                                <div class="inbox-item">
                                    <div class="inbox-img">
                                        {% if i.book.cover_image %}
                                        <img src="{{ i.book.cover_image.url }}"  class="rounded" alt="">
                                        {% else %}
                                        <img class="img-fluid" src="{% static 'assets/images/book3.jpeg' %}" alt="About the image">
                                        {% endif %}
                                    </div>
                                    <div class="inbox-item-info">
                                        <p class="author">{{ i.book.book_title }}</p>
                                        <p class="inbox-message"><b>Book Sub-title: </b>{{ i.book.subbook_title }}</p>
                                        <p class="inbox-date text-primary">{{ i.issue }}</p>
                                        <div class="hover_action">
                                            <button class="btn btn-neutral" data-target="#view{{ forloop.counter }}" data-toggle="modal"><i class="zmdi zmdi-eye col-primary"></i></button>

                                        </div>
                                    </div>
                                </div>

                            </li>
                            {% endfor %}




                        </ul>
                    </div>
                </div>
                 </div>
            <div class="col-sm-12 col-md-12 col-lg-6">
                <div class="card">
                    <div class="header">
                        <h2><strong>Today's </strong>Details</h2>

                    </div>
                    <div class="body">
                       <ul class="row profile_state list-unstyled">
                        <li class="col-lg-6 col-md-4 col-6">

                                <i class="zmdi zmdi-bookmark col-pink"></i>
                                <h4>{{ todys_issued_book }}</h4>
                                <span>Issued Books</span>

                        </li>
                           <li class="col-lg-6 col-md-4 col-6">

                                <i class="zmdi zmdi-bookmark col-green"></i>
                                <h4>{{ todays_return_book }}</h4>
                                <span> Returned Books</span>

                        </li>

                       </ul>
                    </div>
                </div>
                 <div class="row clearfix">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2><strong>Last </strong>Added Book</h2>

                        </div>
                        <div class="body">
                        <ul class="new_friend_list list-unstyled row">
                            {% for i in last_five_add %}
                            <li class="col-lg-4 col-md-2 col-sm-6 col-4">
                                <a href="{% url 'LibraryPanel:Library_book_details' i.id %}">
                                    {% if i.cover_image %}
                                        <img id="blah"   src="{{ i.cover_image.url }}" height="60" width="100"  />
                                        {% else %}
                                        <img id="blah"  src="{% static 'assets/images/book3.jpeg' %}" >
                                        {% endif %}
                                    <h6 class="users_name">{{ i.book_title }}</h6>
                                    <small class=" col-primary">{{ i.created_date }}</small>
                                </a>
                            </li>
                            {% endfor %}

                        </ul>
                        </div>
                    </div>
                </div>
        </div>
                 </div>


            </div>

    </div>
</section>
 {% for i in last_five %}
<div class="modal fade" id="view{{ forloop.counter }}" tabindex="-1" role="dialog">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center>
                    <h6 class="title" id="largeModalLabel1111"><strong>Issue Book</strong></h6>
                    </center>

            </div>
            <div class="modal-body">
                <ul class="comment-reply list-unstyled">
                            <li class="row">
                                <div class="icon-box col-md-4 col-4">
                                    <img class=" img-thumbnail" src="{{ i.student.image.url }}" >
                                </div>
                                <div class="text-box col-md-8 col-8 p-l-0 p-r0">
                                    <h5 class="m-b-0 col-teal">{{ i.student.name }} </h5>
                                    <p><b>Roll Number: </b> {{ i.student.roll_number }}<br>
                                        <b>Expected Return date: </b> {{ i.Due }}

                                    </p>

                                    <ul class="list-inline">
                                        <li> </li>
                                        <li></li>
                                    </ul>
                                </div>
                            </li>


                        </ul>

            </div>
        </div>
                </div>

        </div>
{% endfor %}
<script>
function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(120);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

</script>
<!-- Jquery Core Js -->
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->

<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
{% endblock %}
</body>

<!-- Mirrored from thememakker.com/templates/oreo/university/html/blank.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 17 Sep 2018 02:53:19 GMT -->
</html>

LibraryPanel/templates/Library/master_book.html
{% extends 'Library/base.html' %}

{% block up %}


<html class="no-js " lang="en">

<!-- Mirrored from thememakker.com/templates/oreo/university/html/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 17 Sep 2018 02:52:22 GMT -->
<head>
{% load static %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">

<title>{{ ins_data.name }} - All Books</title>
<!-- Favicon-->
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
<!-- Custom Css -->
<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
<link href="{% static 'assets/plugins/jquery-datatable/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>
{% endblock %}

{% block down %}

<!-- Main Content -->
{% if opt == 'error' %}
<script>
    alert(' This RollNumber is not exists ');
</script>
{% endif %}
<section class="content profile-page">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>All Books
               
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">                
                
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{% url 'LibraryPanel:Library_add_books' 'ALL' %}" ><i class="zmdi zmdi-plus-square"></i> &nbsp;Add Book</a></li>
                   
                </ul>                
            </div>
        </div>
    </div>    
  <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card student-list">
                    <div class="header">
                        <h2><strong>Books</strong> List</h2>
                                            </div>
                    <div class="body widget tag-clouds">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
										 <th>Book Name</th>
                                        <th>Category</th>
										<th>Sub-Category</th>
                                        <th>ISBN Number</th>
                                        <th>In Stock</th>
                                        <th>Details</th>
                                        <th>Issue Book</th>
                                        <th>Delete</th>

                                    </tr>
                                </thead>
                                <tbody>
								{% for book in all_book %}
                                {% if book.category or book.subcategory %}
                                    <tr>

                                        <td>&nbsp;&nbsp;&nbsp;{{ forloop.counter }}</td>
										<td>{{ book.book_title }}</td>
                                        <td>{{ book.category.name }}</td>
										<td>{{ book.subcategory.name }}</td>
                                        <td>{{ book.ISBN }}</td>
                                        <td>{{ book.ave_copy }}</td>
                                        <td><a href ="{% url 'LibraryPanel:Library_book_details' book.id %}"><span class="badge bg-info">Details</span></a></td>
                                        {% if book.ave_copy != '0' %}
                                        <td style="text-align:center"><button class=" btn  badge bg-warning" data-toggle="modal" data-target="#IssueBook{{ forloop.counter }}"><b>Issue</b></button></td>
                                        {% else %}
                                        <td style="text-align:center"><button class=" btn badge bg-warning" onclick="myFunction();"><b>Issue</b></button></td>

                                        {% endif %}
                                        {% if book in li %}
                                        <td><button class=" btn badge bg-danger" onclick="myFunction2();"><b>Delete</b></button></td>

                                        {% else %}
                                        <td><a href ="{% url 'LibraryPanel:delete_for_all' book.id 'Book' %}"><button class=" btn badge bg-danger"><b>Delete</b></button></a></td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                                {% endfor %}
                                 </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
{% for book in all_book %}
<div class="modal fade" id="IssueBook{{ forloop.counter }}" tabindex="-1" role="dialog">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center>
                    <h6 class="title" id="largeModalLabel1111"><strong>Issue Book</strong></h6>
                    </center>

            </div>
            <div class="modal-body">
                <form class="form" action="{% url 'LibraryPanel:filter_roll_number' %}" method="post" enctype="multipart/form-data"
                >
                {% csrf_token %}

                <div class="form-group">
                   <label><b>Enter RollNumber</b></label>
                    <div class="form-line">
                        <input type="text" class="form-control" name="roll_number" placeholder="Enter RollNumber" required="required" >
                    </div>
                    <div class="form-line">
                        <input type="hidden" class="form-contdocrol" name="book_id" value="{{ book.id }}">
                    </div>
                </div>

                <center>
                <input type="submit" class="btn btn-primary btn-round waves-effect" value="Submit" >
                </center>

               </form><br><br>


            </div>
        </div>
                </div>

        </div>

{% endfor %}
<script>
    function myFunction() {
    alert("This Book out of stock you can't issue it");
    }
</script>
<script>
    function myFunction2() {
    alert("This Book is issued by someone. So, you can not delete it now...");
    }
</script>
<!-- Jquery Core Js -->
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js -->

<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/datatablescripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/pages/tables/jquery-datatable.js' %}"></script>

{% endblock %}
</body>

<!-- Mirrored from thememakker.com/templates/oreo/university/html/blank.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 17 Sep 2018 02:53:19 GMT -->
</html>